language: objective-c
osx_image: xcode8
before_install:
- gem install cocoapods -v '1.1.0.rc2.2' 
script:
- set -o pipefail && xcodebuild test -workspace Example/RichTextVC-iOS.xcworkspace -scheme RichTextVC-iOS-Example -sdk iphonesimulator9.3 -destination 'OS=9.3,device=iPhone 5,platform=iOS Simulator' | xcpretty
- pod lib lint
