language: swift
osx_image: xcode10.1
notifications:
  slack: lyokotech:7AmemNHORB2ShidELPFrYeUO
  email: false
before_install:
- gem install cocoapods -v '1.5.3' 
script:
- set -o pipefail && xcodebuild clean build -workspace Example/RichTextVC-iOS-Example.xcworkspace -scheme RichTextVC-iOS-Example -sdk iphonesimulator -destination 'name=iPhone 8,platform=iOS Simulator' | xcpretty
- pod lib lint
